# -*- coding: utf-8 -*-
"""pcolor.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JlYbqcdgDkO0iDYFbOZVbm0N5_GEnKkO
"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import matplotlib.pyplot as plt
import numpy as np

data = np.random.rand(5,6)

plt.pcolor(data)

plt.show()

plt.pcolor(data, cmap ='YlGnBu_r')
plt.show()

N = 100
X, Y = np.meshgrid(np.linspace(-5,5,N),
                   np.linspace(-4,4,N))

Z = X**2 + Y**2

plt.pcolor(X,Y,Z, cmap = 'YlGnBu_r')

plt.show()

nrows = ncols = 5
x = np.arange(ncols + 1)
y = np.arange(nrows + 1)

z = np.arange(nrows*ncols).reshape(nrows, ncols)

plt.pcolormesh(x,y,z, shading = 'flat', cmap = 'coolwarm')

plt.show()

plt.pcolormesh(x, y, z, shading = 'auto', cmap = 'cool')

plt.show()

z = np.random.rand(6,10)

x = np.arange(0,10,1)

y = np.arange(4,10,1)

T = 0.5

X, Y = np.meshgrid(x,y)

X = X + T*Y

Y = Y + T*X



plt.pcolormesh(X, Y, z, shading = 'auto', cmap = 'cool')#plt.pcolormesh(X, Y, Z, shading = 'auto', cmap = 'cool')

plt.show()

N = 100
X, Y = np.meshgrid(np.linspace(-5,5,N),
                   np.linspace(-5,5,N))

Z = (X**2 + Y**2)

img = plt.imshow(Z, cmap = 'YlGnBu_r')
plt.colorbar(img)

plt.show()

img = plt.imshow(Z, cmap = 'coolwarm')

plt.colorbar(img,  shrink = 0.6)

plt.show()

img = plt.imshow(Z, cmap = 'coolwarm')
plt.colorbar(img,extend= 'both')
plt.show()

